# 딥러닝
- framework
    - Tensorflow
        - keras
            - Sequential API
                - 선형회귀
                - logistic 회귀
                - Multi-Class
            - Functional API
            

## Multi-Class

Multi-Class는 3개 이상의 output에서 가장 확률이 높은 클래스를 고르는 것이다.
Multi-Class 분류에 필요한 기술  
    - one-hot encoding  
    - softmax function

## one-hot encoding
> target의 형태를 클래스 수만큼 나눈다.
- 사용 방법  
    > from tensorflow.keras.utils import to_categorical  
    > y = to_categorical(y, n)  -> n은 클래스 수

## softmax function
$ y_k = \frac{exp(a_k)}{\sum_{i}^{n}(exp(a_i))} $
> softmax는 3개 이상으로 분류되는 Multi-Class 분류에서 사용되는 활성화 함수이다.  
> softmax는 input 값을 output으로 [0,1]의 범위의 값으로 정규화 하며 모든 output의 합은 1이 되게 해주는 함수이다.  
Ex) output이 3개 -> 각각의 값이 0.8, 0.7, 0.4 인 경우 각 확률의 총합이 확률의 범위인 [0,1]을 넘어가기 때문에 softmax를 사용하여 0.7, 0.2, 0.1로 확률의 범위로 변환해주는 기능


## 실습

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import load_iris

In [ ]:
data = load_iris()
x = data.data
y = data.target

In [ ]:
# one-hot 인코딩
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, 3)

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

In [ ]:
# Multi-Class Sequential API
# 세션 클리어
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 레이어 쌓기
model.add(keras.layers.Input(shape=(4, )))
model.add(keras.layers.Dense(3, activation='softmax'))

In [ ]:
# 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [ ]:
# 모델 학습
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
5/5 [==============================] - 1s 6ms/step - loss: 1.7924 - accuracy: 0.0933
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.7581 - accuracy: 0.0867
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.7248 - accuracy: 0.0800
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6890 - accuracy: 0.0800
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6583 - accuracy: 0.0733
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6253 - accuracy: 0.0733
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5944 - accuracy: 0.0733
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 1.5633 - accuracy: 0.0733
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5334 - accuracy: 0.0733
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 1.5012 - accuracy: 0.0733
Epoch 11/100
5/5 [===========

In [ ]:
# 모델 성능 비교
print('정답')
print(y[:10])
print('='*80)
print('모델이 예측한 값')
print(model.predict(x)[:10])

정답
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
모델이 예측한 값
5/5 [==============================] - 0s 3ms/step
[[0.77422845 0.02628164 0.19949001]
 [0.6587341  0.05299972 0.28826624]
 [0.750597   0.03448304 0.21491991]
 [0.71292424 0.04877003 0.2383057 ]
 [0.80633193 0.02199154 0.17167647]
 [0.80229837 0.01942403 0.17827775]
 [0.79535526 0.02672158 0.17792316]
 [0.7502094  0.03354248 0.21624796]
 [0.6895237  0.05663347 0.2538427 ]
 [0.6819483  0.05313057 0.2649211 ]]
