# 은닉층(히든 레이어)
히든 레이어와 노드는 무슨 역할을 하는가?
1. 레이어가 쌓일수록 low level ~ high level의 특징을 새롭게 뽑아내는 것
2. 노드의 수는 해당 level에서 연결된 것으로부터 새롭게 추출하려는 feature의 수
- 즉 히든 레이어는 연결된 것으로 부터 기존에 없던 새로운 feature을 추출, 재표현 하는 역할 => Feature Representation

## 실습

In [4]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris

In [7]:
data = load_iris()

In [9]:
# target과 data 나누기
x = data.data
y = data.target

In [10]:
# shape 확인
x.shape, y.shape

((150, 4), (150,))

In [11]:
# target 확인
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
# 학습데이터, 평가데이터 분리 7:3 으로 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [13]:
# 전처리 : one-hot encoding
len_unique_y = len(np.unique(y_train))
y_train = to_categorical(y_train, len_unique_y)
y_test = to_categorical(y_test, len_unique_y)

In [14]:
x_train.shape, y_train.shape

((105, 4), (105, 3))

In [16]:
# 세션 초기화
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 레이어 블록 조립
# 히든 레이어 2개, 노드 수 각각 : 32개 
model.add(keras.layers.Input(shape=(4,)))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(3, activation='softmax'))

In [21]:
# 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# 모델 요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 모델 학습
model.fit(x_train, y_train, epochs=100, verbose=1)

Epoch 1/100
4/4 [==============================] - 1s 6ms/step - loss: 1.5342 - accuracy: 0.3810
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.2743 - accuracy: 0.5333
Epoch 3/100
4/4 [==============================] - 0s 7ms/step - loss: 1.0888 - accuracy: 0.6571
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9669 - accuracy: 0.6857
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9332 - accuracy: 0.6476
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9069 - accuracy: 0.5905
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8838 - accuracy: 0.6571
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8535 - accuracy: 0.6571
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8154 - accuracy: 0.6571
Epoch 10/100
4/4 [==============================] - 0s 7ms/step - loss: 0.7864 - accuracy: 0.6286
Epoch 11/100
4/4 [===========

In [24]:
# 성능 학인
y_pred = model.predict(x_test)
print('정답 :')
print(y_test[:15])
print('='*80)
print('모델 예측값:')
print(y_pred[:15])

2/2 [==============================] - 0s 6ms/step
정답 :
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
모델 예측값:
[[2.4416124e-02 9.1002595e-01 6.5557897e-02]
 [1.6605976e-04 1.0051615e-01 8.9931774e-01]
 [9.7612572e-01 2.3842268e-02 3.1998039e-05]
 [8.7174335e-03 8.8311762e-01 1.0816492e-01]
 [9.9168658e-01 8.3080744e-03 5.4398911e-06]
 [9.9740537e-05 1.9127020e-01 8.0862999e-01]
 [6.1975788e-06 3.2171682e-02 9.6782207e-01]
 [8.7224405e-05 1.9174580e-01 8.0816704e-01]
 [9.7996604e-01 2.0003572e-02 3.0305167e-05]
 [4.4592074e-03 9.3091768e-01 6.4623103e-02]
 [5.9184516e-05 7.4909158e-02 9.2503160e-01]
 [9.8436266e-01 1.5619123e-02 1.8152941e-05]
 [9.9412233e-01 5.8743395e-03 3.2437395e-06]
 [1.1689481e-02 9.2466521e-01 6.3645184e-02]
 [4.1990159e-03 7.0421225e-01 2.9158866e-01]]
