# Sentiment Classification & Embedding II

* Embedding Layer
* Sequence Model

# 01. What data we use?

In [ ]:
!pip install konlpy pandas seaborn gensim wordcloud python-mecab-ko wget

In [ ]:
# MeCab 사전 설치
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git
!bash Mecab-ko-for-Google-Colab/install_mecab-ko_on_colab190912.sh

In [ ]:
!pip install konlpy
!pip install mecab-python3

In [ ]:
# MeCab 설치
!apt-get update
!apt-get install g++ openjdk-8-jdk python-dev python3-dev
!pip install customized_konlpy

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import pandas as pd

In [3]:
data= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AIVLE/ProjectAIVLE/project4/train.csv')

In [4]:
data.head()

text label
0  self.convs1 = nn.ModuleList([nn.Conv2d(1, Co, ...   코드2
1  현재 이미지를 여러개 업로드 하기 위해 자바스크립트로 동적으로 폼 여러개 생성하는데...     웹
2  glob.glob(PATH) 를 사용할 때 질문입니다.\n\nPATH에 [ ] 가 ...   코드2
3  tmpp = tmp.groupby(by = 'Addr1', as_index=Fals...   코드2
4  filename = TEST_IMAGE + str(round(frame_sec)) ...   코드2

In [5]:
data['new_label'] = data['label'].apply(lambda x: '코드' if x.startswith('코드') else x)

In [33]:
data.head()

text label new_label
0  self.convs1 = nn.ModuleList([nn.Conv2d(1, Co, ...   코드2        코드
1  현재 이미지를 여러개 업로드 하기 위해 자바스크립트로 동적으로 폼 여러개 생성하는데...     웹         웹
2  glob.glob(PATH) 를 사용할 때 질문입니다.\n\nPATH에 [ ] 가 ...   코드2        코드
3  tmpp = tmp.groupby(by = 'Addr1', as_index=Fals...   코드2        코드
4  filename = TEST_IMAGE + str(round(frame_sec)) ...   코드2        코드

In [6]:
data = pd.get_dummies(data, columns = ['new_label'], drop_first = False)

In [7]:
target = ['new_label_시스템 운영', 'new_label_원격', 'new_label_웹', 'new_label_이론', 'new_label_코드']
x = data['text']
y = data[target]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=486)

In [ ]:
x_train

In [ ]:
x_test

In [9]:
x_train.reset_index(drop=True, inplace=True)
x_test.reset_index(drop=True, inplace=True)

# (Skip) : 한국어 기본 전처리

In [16]:
# !pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
# # train_data=train_data.dropna(how='any')
# x_train = x_train.str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
# # 한글과 공백을 제외하고 모두 제거
# x_train[:5]

<ipython-input-13-48f28a415dcb>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  x_train = x_train.str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")


0    아래 내용처럼 작성했었는데 실습 의 가치 제안 부분을 모르겠어서 오늘 실습을 못따라...
1    지난 차 프로젝트에서 조별 과제를 제출할 수 있는 섹션이 조별 과제 시간 조별 발표...
2    에 서브넷을 만들 때 프라이빗 개퍼블릭 개씩프라이빗과 퍼블릭을 각각 만들어 주는 이...
3           혹시 녹화본을 원테이크로 촬영해야하는지 나누어서 녹화해도 되는지 문의드립니다
4    영구적으로 정책을 적용하는 경우에는 각각 설정하는 개인과 개인을 그룹으로 넣어 설정...
Name: text, dtype: object

In [17]:
# import re
# clean_text = []
# for i in range(len(x_train)):
#     clean_text.append(re.sub(r'[^\w\s]', '', x_train[i]))
# x_train = clean_text
# x_train[:5]

['아래 내용처럼 작성했었는데 실습5 6의 가치 제안 부분을 모르겠어서 오늘 실습을 못따라가고 있어서 그런데 도와주실 수 있으신가요',
 '지난 1차 프로젝트에서 조별 과제를 제출할 수 있는 섹션이\n1 조별 과제 시간\n2 조별 발표 시간\n위 2가지로 나뉘어 있습니다 4반 16조는 조별과제 발표 시간에 발표까지 진행했었는데요\n 2조별발표 섹션에는 PPT 파일을 업로드하지 못했습니다 조별과제 PPT를 1조별과제 섹션에만 업로드해도 됐던 것인지 문의드립니다 ',
 'vpc에 서브넷을 만들 때 \n프라이빗 2개\n퍼블릭 2개씩\n프라이빗과 퍼블릭을 각각 만들어 주는 이유는 뭔가요\n한번에 4개를 추가해서 만들 수는 없는지 실습 편의상 구분해서 만든건지 궁금합니다 \n',
 '혹시 녹화본을 원테이크로 촬영해야하는지 나누어서 녹화해도 되는지 문의드립니다',
 '영구적으로 정책을 적용하는 경우에는 각각 설정하는 개인과 개인을 그룹으로 넣어 설정할 수 있는 방법처럼\n임시로 적용하는 ROLE의 경우에도 각각 지정하거나 그룹으로 만들어 ROLE을 적용시킬 수 있나요\n아니면 ROLE은 접근하는 개인에 대해 하나하나 적용 시켜야하는건가요']

In [18]:
# import re
# clean_text = []
# for i in range(len(x_test)):
#     clean_text.append(re.sub(r'[^\w\s]', '', x_test[i]))
# x_test = clean_text
# x_test[:5]

['추가해서 질문드립니다\n같은 옵션과 코드를 가지고 돌리는데\n돌릴 때마다 결과가 다른 경우는 무엇 때문인가요\n예를 들어 딥러닝 코드를 노드수 레이어수 epochs 등을 똑같이 맞추었을 때 그래프와 검증 값이 다르게 나옵니다',
 '관련여부를 p_value 로 확인하면 될텐데 굳이 자유도가 필요한 이유가 있을까요',
 '안녕하세요 실습5번의 마지막 부분을 하다가 제 아이디로 되어져 있는 웹서버의 인스턴스를 종료 했는데 다시 재시작하는 방법이 있을까요',
 ' 모델 학습\nhistory  modelfit\n    train_generator\n    epochs1000\n    verbose1\n    validation_datavalidation_generator\n    callbacksearly_stopping checkpoint\n\n\n이렇게 코드 작성하여 실행시켰더니 오류가 발생하였습니다\n오류 화면은 첨부파일로 첨부하였습니다\ntrain_generator와 validation_generator 부분은 강사님과 동일하게 작성하였습니다\n혹시 어느 부분을 어떻게 수정하면 될지 가르쳐주시면 감사하겠습니다',
 '가이드대로 test_gen 을 만들고 예측을 진행했는데 모두 sam을 예측하는 결과가 나왔습니다 그래서 test data에서 문제가 있다고 생각하게 되었는데 혹시 label이 존재하면 안되는 건지 아니면 test label이 각각 나뉘어있어야 하는지 알려주시면 감사드리겠습니다 \n그리고 어떻게 방향을 잡아야 하는지 알려주시면 감사하겠습니다\n']

In [19]:
# import konlpy
# from konlpy.tag import Okt
# okt = Okt()
# stopwords=['의','가','이','은','들','는','좀','잘','걍','과','도','를','으로','자','에','와','한','하다', "안녕", "감사", 'ㅠㅠ', '습니다', 'ㅎㅎ', '합니다', ]

In [20]:
# # from mecab import MeCab
# from mecab import MeCab

# mecab_ko = MeCab()

In [ ]:
# pos = mecab_ko.pos(text)

In [ ]:
# X_train=[]
# for i in x_train:
#     temp = mecab_ko.morphs(i)
#     temp_X=[word for word in temp_X if not word in stopwords]
#     X_train.append(temp)


In [21]:
# X_train=[]
# for i in x_train:
#     temp = mecab_ko.morphs(i)
#     # temp2 = ' '.join(temp)
#     X_train.append(temp)

In [27]:
# %%time

# X_train=[]
# for sentence in x_train:
#     temp_X = []
#     temp_X=okt.morphs(sentence, stem=True) # 토큰화
#     temp_X=[word for word in temp_X if not word in stopwords] # 불용어 제거
#     X_train.append(temp_X)

CPU times: user 13 s, sys: 31.7 ms, total: 13 s
Wall time: 12.7 s


In [ ]:
# X_train

In [23]:
# %%time

# X_train=[]
# for sentence in x_train:
#     temp_X = []
#     temp_X=okt.morphs(sentence, stem=True) # 토큰화
#     temp_X=[word for word in temp_X if not word in stopwords] # 불용어 제거
#     X_train.append(temp_X)

CPU times: user 19.3 s, sys: 61.3 ms, total: 19.4 s
Wall time: 14.1 s


In [ ]:
# print(X_train[:4])

In [24]:
# # x_test=test_data.dropna(how='any') # Null 값 제거
# x_test = x_test.str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","") # 정규 표현식 수행

# X_test=[]
# for sentence in x_test:
#     temp_X = []
#     temp_X=okt.morphs(sentence, stem=True) # 토큰화
#     temp_X=[word for word in temp_X if not word in stopwords] # 불용어 제거
#     X_test.append(temp_X)

<ipython-input-24-92bd89e97250>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  x_test = x_test.str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","") # 정규 표현식 수행


In [23]:
# X_test=[]
# for i in x_test:
#     temp = mecab_ko.morphs(i)
#     # temp2 = ' '.join(temp)
#     X_test.append(temp)

# Tokenizing & Text to Sequences

In [10]:
import nltk
from nltk import ngrams
from sklearn.feature_extraction.text import CountVectorizer
ngram_range=(2,2)

In [11]:
## 위의 한국어 전처리를 했다면 사용하지 않는다.
## 명확히 str으로 데이터 타입을 변경해줘야 tokenizer에서 에러가 없다.
## 한국어 건들때만 그러는 것 같음.
X_train = x_train.astype('str').tolist()
X_test = x_test.astype('str').tolist()

In [ ]:
X_train[:4]

In [ ]:
X_train[1]

In [12]:
y_train = y_train.values
y_test = y_test.values

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer
max_words = 40000   # 상위 40,000개의 단어만 보존
tokenizer = Tokenizer(num_words=max_words, lower=False)  # lower(대문자->소문자) 옵션은, 한국어를 할땐 끄자.

In [14]:
tokenizer.fit_on_sequences(X_train)

In [ ]:
X_train[:3]

In [43]:
# tokenizer.texts_to_sequences(X_train[:3])

[[], [], []]

In [15]:
%%time
tokenizer.fit_on_texts( X_train )
x_train = tokenizer.texts_to_sequences(X_train)
x_test = tokenizer.texts_to_sequences(X_test)

CPU times: user 507 ms, sys: 13.8 ms, total: 520 ms
Wall time: 516 ms


In [27]:
# from tensorflow.keras.preprocessing.text import Tokenizer
# tokenizer2 = Tokenizer(num_words=5)

# texts = ['가 나 다 라 마']

In [28]:
# tokenizer2.fit_on_texts(texts)
# tokenizer2.texts_to_sequences(texts)  
# ## 왜 상위 5개단어를 했는데 왜 상위 4개만 된걸까?
# ## 0번 인덱스의 의미 탐구.

In [29]:
# tokenizer2.index_word

In [45]:
tokenizer.index_word[602]

'grid'

In [46]:
tokenizer.index_word[8]

'수'

In [32]:
tokenizer.index_word[705]

'시스템'

In [16]:
# 문장 최대 길이 구하기
text_lengths = [len(data) for text in data]
data['text'].apply(len).max()

6012

# Padding Sequence

In [17]:
max_words = max_words ## 위에서 설정하길 35000
embedding_dim = 128 ## 단어 embedding 차원
max_len = 6012 ## 문장 최대 길이

In [18]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
x_train

In [19]:
x_train = pad_sequences(x_train, maxlen = max_len)
x_test = pad_sequences(x_test, maxlen = max_len)

In [88]:
x_train[0]

array([   0,    0,    0, ...,    9, 2047,  460], dtype=int32)

In [38]:
x_train[0]

array([ 0,  0,  0, ...,  8,  2, 89], dtype=int32)

In [ ]:
y_train

In [59]:
np.unique(y_train)

array([0, 1], dtype=uint8)

In [40]:
# train_data.iloc[2]

In [20]:
x_train = np.array(x_train)
x_test = np.array(x_test)

# 0으로 가득찬 데이터에 대한 추가 전처리

In [52]:
not0train_idx = x_train.sum(1) > 0
not0test_idx = x_test.sum(1) > 0

# train_data.iloc[:10]
# x_train[:10].sum(1)
# x_train[:10].sum(1)>0
# train_data
# train_data.loc[not0train_idx]

In [ ]:
# x_train = x_train.loc[not0train_idx].reset_index(drop=True)
# x_test = x_test.loc[not0test_idx].reset_index(drop=True)

In [44]:
# x_train = x_train[not0train_idx]
# y_train = y_train[not0train_idx]

# x_test = x_test[not0test_idx]
# y_test = y_test[not0test_idx]

# 모델링

In [21]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.layers import Dense, Flatten, Conv1D, MaxPool1D
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, SimpleRNN, GRU

from tensorflow.keras.models import Sequential

임베딩 레이어에 남이 만든 임베딩값 집어넣기 : [ 좋은 공식 문서 ](https://keras.io/examples/nlp/pretrained_word_embeddings/)

In [22]:
x_train.shape, y_train.shape

((2964, 6012), (2964, 5))

In [78]:
# # 0.6509364101371774
# keras.backend.clear_session()

# model = Sequential()

# model.add(Embedding( max_words, # 사용할 총 token개수
#                     embedding_dim, # 한 token당 몇차원(몇개)의 특징값으로 바꾸어낼 것인가.
#                     input_length=max_len )) # 통일한 문장 길이

# model.add(Conv1D(128, 5, activation='swish')) 
# forward_layer = LSTM(32, return_sequences=True )
# # forward_layer = GRU(128, return_sequences=True )
# backward_layer = GRU(32, return_sequences=True, go_backwards=True)
# model.add(Bidirectional(forward_layer, backward_layer=backward_layer))
# model.add(Bidirectional(GRU(128, return_sequences=True)))
# model.add(Flatten())
# model.add(Dense(128, activation='swish'))
# model.add(Dense(64, activation='swish'))
# model.add(Dense(5, activation='softmax'))

# model.compile(loss = 'categorical_crossentropy',
#               optimizer = keras.optimizers.Adam(),
#               metrics = 'accuracy')

In [72]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 6012, 128)         5120000   
                                                                 
 conv1d (Conv1D)             (None, 6008, 128)         82048     
                                                                 
 bidirectional (Bidirectiona  (None, 6008, 256)        230656    
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 6008, 256)        296448    
 nal)                                                            
                                                                 
 flatten (Flatten)           (None, 1538048)           0         
                                                                 
 dense (Dense)               (None, 64)                9

In [23]:
from tensorflow.keras.callbacks import EarlyStopping

In [24]:
es = EarlyStopping(monitor='val_loss',
                   min_delta=0,
                   patience=5,
                   verbose=1)

In [ ]:


model.fit(x_train, y_train, epochs=100, batch_size=64, # 일반적으로 이렇게 크게 주진 않는다.
          validation_split=0.2, verbose =1,
          callbacks=[es])

In [ ]:
model.evaluate(x_test, y_test)

In [32]:
from sklearn.metrics import f1_score

In [82]:
y_pred = model.predict(x_test)

24/24 [==============================] - 7s 251ms/step


In [63]:
y_pred.shape

(742, 5)

In [64]:
y_test.shape

(742, 5)

In [ ]:
# y_pred = np.argmax(y_pred, axis=1)
# y_test = np.argmax(y_test, axis=1)

In [86]:
f1_score(y_test, y_pred, average='macro')  # 다중 분류 문제에서는 'macro' 또는 'weighted' 사용

0.6509364101371774

In [ ]:
y_pred.shape

In [87]:
f1_mean = f1_score(y_test, y_pred, average=None).mean()
print(f1_mean)

0.6509364101371774


In [88]:
f1_score(y_test, y_pred, average=None)

array([0.67647059, 0.5       , 0.63768116, 0.6375    , 0.8030303 ])

In [ ]:
y_pred

## 모델 2

In [29]:
max_words = max_words ## 위에서 설정하길 35000
embedding_dim = 128 ## 단어 embedding 차원
max_len = 6012 ## 문장 최대 길이

In [45]:
# 0.
keras.backend.clear_session()

model2 = Sequential()

model2.add(Embedding( max_words, # 사용할 총 token개수
                    embedding_dim, # 한 token당 몇차원(몇개)의 특징값으로 바꾸어낼 것인가.
                    input_length=max_len )) # 통일한 문장 길이

model2.add(Conv1D(128, 5, activation='swish')) 
forward_layer = LSTM(32, return_sequences=True )
# forward_layer = GRU(128, return_sequences=True )
backward_layer = GRU(32, return_sequences=True, go_backwards=True)
model2.add(Bidirectional(forward_layer, backward_layer=backward_layer))
# model2.add(Bidirectional(GRU(128, return_sequences=True)))
model2.add(Flatten())
model2.add(Dense(128, activation='swish'))
model2.add(Dense(32, activation='swish'))
# model2.add(Dense(128, activation='swish'))
model2.add(Dense(5, activation='softmax'))

model2.compile(loss = 'categorical_crossentropy',
              optimizer = keras.optimizers.Adam(),
              metrics = 'accuracy')

In [47]:
model2.fit(x_train, y_train, epochs=100, validation_split=0.2, verbose =1, callbacks=[es])

Epoch 1/100
75/75 [==============================] - 29s 384ms/step - loss: 0.0641 - accuracy: 0.9798 - val_loss: 1.3881 - val_accuracy: 0.7015
Epoch 2/100
75/75 [==============================] - 28s 369ms/step - loss: 0.0267 - accuracy: 0.9924 - val_loss: 2.0182 - val_accuracy: 0.6374
Epoch 3/100
75/75 [==============================] - 27s 364ms/step - loss: 0.0123 - accuracy: 0.9975 - val_loss: 1.9247 - val_accuracy: 0.6695
Epoch 4/100
75/75 [==============================] - 28s 371ms/step - loss: 0.0057 - accuracy: 0.9987 - val_loss: 2.0905 - val_accuracy: 0.6644
Epoch 5/100
75/75 [==============================] - 27s 358ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 2.1029 - val_accuracy: 0.6779
Epoch 6/100
75/75 [==============================] - 26s 349ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 2.2468 - val_accuracy: 0.6779
Epoch 6: early stopping


In [41]:
y_pred = model2.predict(x_test)

24/24 [==============================] - 4s 121ms/step


In [42]:
test_pr = y_pred
test_te = y_test

In [43]:
test_pr = np.argmax(y_pred, axis=1)
test_te = np.argmax(y_test, axis=1)

In [44]:
f1_mean = f1_score(test_te, test_pr, average=None).mean()
print(f1_mean)

0.6307102439057124


### 모델링 2

In [ ]:
keras.backend.clear_session()

model = Sequential()

model.add(Embedding( max_words, # 사용할 총 token개수
                    embedding_dim, # 한 token당 몇차원(몇개)의 특징값으로 바꾸어낼 것인가.
                    input_length=max_len )) # 통일한 문장 길이

model.add(Conv1D(128, 5, activation='swish')) 
forward_layer = LSTM(48, return_sequences=True )
backward_layer = GRU(48, return_sequences=True, go_backwards=True)
model.add(Bidirectional(forward_layer, backward_layer=backward_layer))
model.add(Bidirectional(GRU(64, return_sequences=True)))
model.add(Flatten())
model.add(Dense(128, activation='swish'))
model.add(Dense(5, activation='softmax'))

model.compile(loss = 'categorical_crossentropy',
              optimizer = keras.optimizers.Adam(),
              metrics = 'accuracy')

In [ ]:
# review_idx = 456

# temp = test_data.loc[review_idx]
# docu = temp['document']
# label = 'positive' if temp['label'] ==1 else 'Negative'

# print(f"문서 번호 {review_idx}")
# print(label, " : ", docu)
# y_pred = model.predict(x_test[review_idx:review_idx+1])
# label_pred = 'positive' if y_pred[0,0] >=0.5 else 'Negative'
# print(f"모델의 예측 : {label_pred},   prob = {y_pred[0,0]*100:.2f}%")